const base = (title: string, body: string, script: string) => String.raw`<!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title}</title><style>
*{box-sizing:border-box}body{margin:0;background:#07090d;color:#f7f8fb;font-family:system-ui,sans-serif;padding:14px}.app{max-width:560px;margin:auto}.card{background:#11151d;border:1px solid #262d38;border-radius:18px;padding:16px;margin-bottom:12px}button{border:0;border-radius:12px;padding:12px 16px;background:#7357ff;color:#fff;font-weight:800}h1{font-size:24px}.muted{color:#9ca6b5}.board{margin:15px auto;display:grid;gap:4px}.status{font-weight:800;margin:10px 0}.red{background:#e5484d}.yellow{background:#f5c542}.cell{background:#171c26;border-radius:8px;min-height:48px}.ttt{grid-template-columns:repeat(3,80px);justify-content:center}.ttt button{height:80px;font-size:30px;padding:0;background:#171c26}.c4{grid-template-columns:repeat(7,42px);justify-content:center}.c4 button{padding:0;height:42px;border-radius:50%;background:#171c26}.c4 .p1{background:#e5484d}.c4 .p2{background:#f5c542}.controls{display:flex;gap:8px;justify-content:center;flex-wrap:wrap}.input{width:100%;padding:12px;border-radius:12px;border:1px solid #303746;background:#090c12;color:#fff;margin:8px 0}</style></head><body><div class="app"><div class="card"><h1>${title}</h1><div id="status" class="status">Menghubungkan...</div>${body}</div></div><script>
const WS_URL="__WUNO_WS_URL__";let ws;const q=new URLSearchParams(location.search);const game=q.get("game")||"solo";
function connect(){if(!WS_URL){status("Server game belum siap");return}ws=new WebSocket(WS_URL);ws.onopen=()=>{ws.send(JSON.stringify({type:"join",game,room:q.get("room"),player:q.get("player"),name:q.get("name")}));status("Terhubung • tunggu pemain lain")};ws.onmessage=e=>{try{onState(JSON.parse(e.data))}catch{}};ws.onclose=()=>status("Koneksi terputus. Buka game lagi untuk menyambung.")}function send(a){if(ws?.readyState===1)ws.send(JSON.stringify(a))}function status(s){document.getElementById("status").textContent=s}connect();
${script}</script></body></html>`;

export const TTT_HTML = base("⭕ Tic-Tac-Toe • 2 Pemain", '<div id="board" class="board ttt"></div><div class="controls"><button onclick="send({type:location.reload()})">Reset</button></div>', `
let b=Array(9).fill(""),me="",turn="";
function onState(s){if(s.game!=="tictactoe")return; b=s.board||b;me=s.me||me;turn=s.turn||turn;status(s.message||("Kamu: "+me+" • Giliran: "+turn));render()}
function render(){let el=document.getElementById("board");el.innerHTML="";b.forEach((v,i)=>{let x=document.createElement("button");x.textContent=v;x.onclick=()=>send({type:"move",index:i});el.appendChild(x)})}
`);

export const CONNECT4_HTML = base("🔴 Connect Four • 2 Pemain", '<div id="board" class="board c4"></div><div class="controls"><button onclick="send({type:"new"})">Main baru</button></div>', `
let b=Array(42).fill(""),me="",turn="";
function onState(s){if(s.game!=="connect4")return;b=s.board||b;me=s.me||me;turn=s.turn||turn;status(s.message||("Kamu: "+me+" • Giliran: "+turn));render()}
function render(){let el=document.getElementById("board");el.innerHTML="";for(let i=0;i<42;i++){let x=document.createElement("button");x.className=b[i]?("p"+b[i]):"";x.onclick=()=>send({type:"move",col:i%7});el.appendChild(x)}}
`);

export const TETRIS_HTML = String.raw`<!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>body{margin:0;background:#07090d;color:#fff;font-family:system-ui;padding:16px}.card{max-width:500px;margin:auto;background:#11151d;border-radius:18px;padding:16px}.board{display:grid;grid-template-columns:repeat(10,1fr);gap:2px;background:#05070a;padding:5px}.c{aspect-ratio:1;background:#171c26}.f{background:#7357ff}.controls{display:grid;grid-template-columns:repeat(5,1fr);gap:6px;margin-top:8px}button{padding:12px;border:0;border-radius:10px;background:#7357ff;color:#fff;font-weight:800}</style></head><body><div class="card"><h1>🧱 WUNO Tetris</h1><p id="s">Skor 0</p><div id="b" class="board"></div><div class="controls"><button onclick="mv(-1)">←</button><button onclick="rot()">↻</button><button onclick="down()">↓</button><button onclick="hard()">⤓</button><button onclick="mv(1)">→</button></div></div><script>
const W=10,H=20,S=[[[1,1,1,1]],[[1,1],[1,1]],[[0,1,0],[1,1,1]],[[1,0,0],[1,1,1]],[[0,0,1],[1,1,1]],[[1,1,0],[0,1,1]]];let g=Array.from({length:H},()=>Array(W).fill(0)),p,x,y,sc=0,over=0;
function np(){p=S[Math.random()*S.length|0].map(r=>[...r]);x=(W-p[0].length)/2|0;y=0;if(hit(0,0))over=1}function hit(dx,dy,q=p){return q.some((r,j)=>r.some((v,i)=>v&&(x+i+dx<0||x+i+dx>=W||y+j+dy>=H||g[y+j+dy]?.[x+i+dx])))}function merge(){p.forEach((r,j)=>r.forEach((v,i)=>{if(v)g[y+j][x+i]=1}))}function clear(){let n=0;g=g.filter(r=>r.some(v=>!v)?1:(n++,0));while(g.length<H)g.unshift(Array(W).fill(0));sc+=n*n*100}function draw(){let e=document.getElementById("b");e.innerHTML="";for(let j=0;j<H;j++)for(let i=0;i<W;i++){let d=document.createElement("div");d.className="c"+(g[j][i]?" f":"");e.appendChild(d)}p?.forEach((r,j)=>r.forEach((v,i)=>{if(v){let k=(y+j)*W+x+i;e.children[k]?.classList.add("f")}}));document.getElementById("s").textContent=over?"Game Over • Skor "+sc:"Skor "+sc}function step(){if(over)return;if(!hit(0,1))y++;else{merge();clear();np()}draw()}function mv(d){if(!over&&!hit(d,0))x+=d;draw()}function rot(){let q=p[0].map((_,i)=>p.map(r=>r[i]).reverse());if(!hit(0,0,q))p=q;draw()}function down(){while(!hit(0,1))y++;step()}function hard(){down()}np();draw();setInterval(step,600);
</script></body></html>`;

export const SPOTIFY_HTML = String.raw`<!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>body{margin:0;background:#07090d;color:#fff;font-family:system-ui;padding:16px}.card{max-width:500px;margin:auto;background:#11151d;border-radius:18px;padding:18px}input{width:100%;padding:13px;box-sizing:border-box;background:#090c12;color:#fff;border:1px solid #303746;border-radius:12px;margin:10px 0}button{padding:12px;border:0;border-radius:10px;background:#7357ff;color:#fff;font-weight:800}</style></head><body><div class="card"><h1>🎵 WUNO Spotify</h1><p>Cari lagu langsung dari sini.</p><input id="q" placeholder="Nama lagu / artis"><button onclick="go()">Cari di Spotify</button></div><script>function go(){let q=document.getElementById("q").value.trim();if(q)location.href="https://open.spotify.com/search/"+encodeURIComponent(q)}</script></body></html>`;
